### PR TITLE
Go from player bar to podcast / episode details.

### PR DESCRIPTION
**Pull request by justinctlam**
Refactor the AudioViewManager as a view controller that is a child view controller in the ContainerViewController.
The new AudioOverlayViewController contains the view and presents the detail podcast view controller with functionality to upvote, downvote, or bookmark along with the podcast details.
To expand the detail view, there is a up arrow button that rotates 180 and acts like a down arrow to collapse the view.

This address issues #76

### CODE REVIEW

**Comment by jasonify** [comment]
Nice!

I ran into this issue but unsure if it's related to this PR or existing problem, will have to investigate further:

https://github.com/SoftwareEngineeringDaily/se-daily-iOS/issues/96


Maybe it was just a very random occurrence / edge case.

-----------

Also, I am wondering if there is a simple way to not show the arrow/button if you are  already viewing the episode that is in the player ?

**Comment by justinctlam** [comment]
I saw it too! Are you only seeing it when testing my PR? 

I'll look into hiding the arrow if already viewing the episode

**Comment by jasonify** [comment]
Yeah, while I was testing your changes I saw it be buggy but I haven't investigated how that code works so not sure why it happened at all. Doesn't seem like your code should affect that though.

**Review by themisterholliday — APPROVED** [review]

**Comment by TheHollidayInn** [comment]
Do you mind updating the merge conflicts now? I just merged in Jason's PR.

**Comment by justinctlam** [comment]
Conflicts resolved

**Comment by TheHollidayInn** [comment]
GTG. Thanks for the PR!

**Pull request merged**
