### PR TITLE
API Tests

### PR DESCRIPTION
**Pull request by berkmolla**
Mostly tests but also made the API class a non-singleton in preparation for a future PR to remove singletons.

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks for the tests! I like the NetworkService as well. I believe you are implementing an Adapter pattern, correct?

Also, why do you suggest we remove singletons?

**Comment by TheHollidayInn** [comment]
Hmm. I did a quick search, and I did find this: https://medium.com/@johnsundell/avoiding-singletons-in-swift-5b8412153f9b :P

**Comment by justinctlam** [comment]
Watch this Google talk on Singletons and you will never use one ever again, or at least ask yourself if you really need it. https://www.youtube.com/watch?v=-FRm3VPhseI

**Comment by berkmolla** [comment]
Haha yup, those two links probably explain it much better than I can :) As for the NetworkService, yeah it is kind of adapter-like, but not really a good one since it uses Alamofire types as parameters. I was going to use that NetworkService protocol to inject a network service into the initializer as well as mock the network calls in the tests but it ended up being kind of fiddly with Alamofire. Will try to find a nice way of doing it and update it.

**Comment by berkmolla** [comment]
@TheHollidayInn @justinctlam Fixed the conflict so this is good to go if you guys are happy with it

**Comment by TheHollidayInn** [comment]
My world view has been changed.... I'm so glad you two showed me that :P 


Sorry. I just merged in the Bookmark PR which created a few more collisions. I'll still need to test and review locally, but everything is looking good.

**Comment by berkmolla** [comment]
@TheHollidayInn Alright, fixed :)

**Comment by TheHollidayInn** [comment]
Thanks! I'll have a look tonight

**Comment by TheHollidayInn** [comment]
Looks good, thanks!

**Pull request merged**
