### PR TITLE
Add app review prompt

### PR DESCRIPTION
**Pull request by eddies5**
Here's the app review prompt after fixing merge conflicts.

### CODE REVIEW

**Comment by berkmolla** [comment]
Is there an advantage of using this custom prompt over the new Apple-provided one? I thought Apple were trying to phase out custom app review prompts?

**Comment by eddies5** [comment]
Hi @berkmolla, I incorporated the PopupDialog pod because I found it to be versatile with the animations and various configurations. I thought it better to use this than to recreate something with less functionality.

Apple's new SKStoreReviewController is used here, but it doesn't allow us to capture negative feedback with comments. We capture negative feedback by first asking if they liked the app, if no then they're prompted to send an email to Jeff. If they do like the app then we ask to display Apple's prompt.

Just like the pattern of preprompting users before displaying the system level notifications or location permission prompts you see in various apps, a slight variation applies here in that we want to capture negative feedback and fast-track positive feedback to the App Store.

**Comment by TheHollidayInn** [comment]
@eddies5 Sorry for the delay on this. Do you mind updating the conflicts, and then I can review it?

**Comment by eddies5** [comment]
@TheHollidayInn No worries, I'll update it this weekend for ya.

**Comment by TheHollidayInn** [comment]
Tested locally and it works great! I have to say I really like the way you implemented this.

Also, I can't seem to submit a review, but that might be because I am on the emulator :P

**Comment by eddies5** [comment]
Thanks @TheHollidayInn I appreciate the compliment!

Right, I don't think we can submit real reviews when working in the simulator, https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

I added a pop up when the running device doesn't support email, this is useful especially when working in the simulator.

**Comment by TheHollidayInn** [comment]
Awesome! Works well. Also, feel free to push multiple commits. We squash before merging.

**Pull request merged**
